app = "mega-webdav"
kill_signal = "SIGTERM"
[build]
  dockerfile = "Dockerfile"
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
    HTTPS_ONLY = 1
    PORT=8000
    # DavPassword =  set as secretes flyctl secrets set PassWord=VALUE
    DavUsername = 'admin'  
    # UserName= set as secretes flyctl secrets set PassWord=VALUE
    # PassWord = set as secretes flyctl secrets set PassWord=VALUE